export const WORKSPACE_TYPES = {
  PERSONAL: 'personal',
  BUSINESS: 'business',
};

export const ACCOUNT_INTENTS = {
  WORKSPACE_OWNER: 'workspace_owner',
  GUEST_ONLY: 'guest_only',
};

export const DEFAULT_PERSONAL_MAX_PROJECTS = 2;
export const DEFAULT_PERSONAL_MAX_GUEST_COLLABORATORS_PER_PROJECT = 5;

export const PROJECT_LIMIT_ERROR = 'PROJECT_LIMIT_REACHED';
export const GUEST_COLLABORATOR_LIMIT_ERROR = 'GUEST_COLLABORATOR_LIMIT_REACHED';
export const EXPORT_FEATURE_LOCKED_ERROR = 'EXPORT_FEATURE_LOCKED';
export const CUSTOM_ROLES_LOCKED_ERROR = 'CUSTOM_ROLES_LOCKED';
